version: "3.7"
services:
  openresty:
    container_name: openresty
    build:
      context: ./openresty
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./openresty/etc/supervisor:/etc/supervisor"
      - "./openresty/etc/nginx/conf:/usr/local/openresty/nginx/conf"
      - "./openresty/etc/nginx/html:/usr/local/openresty/nginx/html"
      - "./openresty/etc/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf"
      - "./openresty/etc/modsecurity-crs:/opt/owasp-modsecurity-crs"
      - "./openresty/logs:/usr/local/openresty/nginx/logs"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ulimits:
      core: -1
  dvwa-test:
    image: vulnerables/web-dvwa
    container_name: dvwa-test
    volumes:
      - "dvwa-db:/var/lib/mysql"
  nginx-test:
    build:
      context: ./nginx-test
      dockerfile: Dockerfile
    container_name: nginx-test
    volumes:
      - "./nginx-test/conf:/etc/nginx"
      - "./nginx-test/html:/usr/share/nginx/html"
volumes:
  dvwa-db:
