version: '3.7'
services:
  openresty:
    build:
      context: ./openresty
      dockerfile: Dockerfile
    container_name: openresty
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./openresty/etc/supervisor:/etc/supervisor"
      - "./openresty/etc/openresty/nginx/conf:/usr/local/openresty/nginx/conf"
      - "./openresty/etc/openresty/nginx/html:/usr/local/openresty/nginx/html"
      - "./openresty/etc/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf"
      - "./openresty/etc/modsecurity-crs:/opt/owasp-modsecurity-crs"
  dvwa-test:
    image: vulnerables/web-dvwa
    container_name: dvwa-test
  nginx-test:
    image: nginx:1.17.6
    container_name: nginx-test